// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_PIXEL_COLOR_LOO_HH_
#define _Loop_PIXEL_COLOR_LOO_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "fxp_sqrt.h"
#include "Loop_PIXEL_COLOR_bkb.h"

namespace ap_rtl {

struct Loop_PIXEL_COLOR_LOO : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > pixel;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    Loop_PIXEL_COLOR_LOO(sc_module_name name);
    SC_HAS_PROCESS(Loop_PIXEL_COLOR_LOO);

    ~Loop_PIXEL_COLOR_LOO();

    sc_trace_file* mVcdFile;

    Loop_PIXEL_COLOR_bkb* p_color_array_U;
    fxp_sqrt* grp_fxp_sqrt_fu_126;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > p_color_array_address0;
    sc_signal< sc_logic > p_color_array_ce0;
    sc_signal< sc_lv<17> > p_color_array_q0;
    sc_signal< sc_lv<32> > minimumDistanceIndex_1_reg_90;
    sc_signal< sc_lv<3> > minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter1_minimumDistanceIndex_reg_102;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter7;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter8;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter9;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter10;
    sc_signal< bool > ap_block_state13_pp0_stage0_iter11;
    sc_signal< bool > ap_block_state14_pp0_stage0_iter12;
    sc_signal< bool > ap_block_state15_pp0_stage0_iter13;
    sc_signal< bool > ap_block_state16_pp0_stage0_iter14;
    sc_signal< bool > ap_block_state17_pp0_stage0_iter15;
    sc_signal< bool > ap_block_state18_pp0_stage0_iter16;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter2_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter3_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter4_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter5_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter6_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter7_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter8_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter9_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter10_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter11_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter12_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter13_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter14_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<3> > ap_reg_pp0_iter15_minimumDistanceIndex_reg_102;
    sc_signal< sc_lv<32> > minimumDistance_0_i_s_reg_114;
    sc_signal< sc_lv<9> > pixelRed_cast_i_fu_141_p1;
    sc_signal< sc_lv<9> > pixelRed_cast_i_reg_379;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<9> > pixelGreen_cast_i_fu_155_p1;
    sc_signal< sc_lv<9> > pixelGreen_cast_i_reg_384;
    sc_signal< sc_lv<9> > pixelBlue_cast_i_fu_163_p1;
    sc_signal< sc_lv<9> > pixelBlue_cast_i_reg_389;
    sc_signal< sc_lv<1> > exitcond_i_i_fu_167_p2;
    sc_signal< sc_lv<1> > exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter1_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter2_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter3_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter4_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter5_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter6_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter7_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter8_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter9_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter10_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter11_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter12_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter13_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter14_exitcond_i_i_reg_394;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter15_exitcond_i_i_reg_394;
    sc_signal< sc_lv<3> > i_fu_173_p2;
    sc_signal< sc_lv<3> > i_reg_398;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<8> > colorGreen_reg_408;
    sc_signal< sc_lv<8> > colorBlue_fu_210_p1;
    sc_signal< sc_lv<8> > colorBlue_reg_413;
    sc_signal< sc_lv<9> > number_assign_fu_214_p2;
    sc_signal< sc_lv<9> > number_assign_reg_418;
    sc_signal< sc_lv<17> > tmp_79_fu_286_p2;
    sc_signal< sc_lv<17> > tmp_79_reg_423;
    sc_signal< sc_lv<28> > p_Val2_5_i_fu_292_p2;
    sc_signal< sc_lv<28> > p_Val2_5_i_reg_429;
    sc_signal< sc_lv<12> > tmp_2_reg_439;
    sc_signal< sc_lv<32> > i_0_minimumDistanceI_fu_363_p3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter16;
    sc_signal< sc_lv<32> > distance_0_minimumDi_fu_371_p3;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter6;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter7;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter8;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter9;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter10;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter11;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter12;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter13;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter14;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter15;
    sc_signal< sc_lv<29> > grp_fxp_sqrt_fu_126_in_val_V_read;
    sc_signal< sc_lv<20> > grp_fxp_sqrt_fu_126_ap_return;
    sc_signal< sc_lv<3> > ap_phi_mux_minimumDistanceIndex_phi_fu_106_p4;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<64> > tmp_i_fu_179_p1;
    sc_signal< sc_lv<8> > pixelRed_fu_131_p4;
    sc_signal< sc_lv<8> > pixelGreen_fu_145_p4;
    sc_signal< sc_lv<8> > pixelBlue_fu_159_p1;
    sc_signal< sc_lv<1> > tmp_75_fu_184_p3;
    sc_signal< sc_lv<9> > colorRed_cast_i_cast_fu_192_p3;
    sc_signal< sc_lv<9> > result3_i_fu_228_p0;
    sc_signal< sc_lv<17> > tmp_s_fu_225_p1;
    sc_signal< sc_lv<9> > result3_i_fu_228_p1;
    sc_signal< sc_lv<17> > result3_i_fu_228_p2;
    sc_signal< sc_lv<26> > p_Val2_s_fu_234_p3;
    sc_signal< sc_lv<9> > colorGreen_cast_i_fu_219_p1;
    sc_signal< sc_lv<9> > number_assign_1_fu_246_p2;
    sc_signal< sc_lv<9> > result_11_i_fu_255_p0;
    sc_signal< sc_lv<17> > tmp_1_fu_251_p1;
    sc_signal< sc_lv<9> > result_11_i_fu_255_p1;
    sc_signal< sc_lv<17> > result_11_i_fu_255_p2;
    sc_signal< sc_lv<27> > p_Val2_1_fu_261_p3;
    sc_signal< sc_lv<9> > colorBlue_cast_i_fu_222_p1;
    sc_signal< sc_lv<9> > number_assign_2_fu_273_p2;
    sc_signal< sc_lv<9> > tmp_79_fu_286_p0;
    sc_signal< sc_lv<9> > tmp_79_fu_286_p1;
    sc_signal< sc_lv<28> > p_Val2_cast_i_fu_242_p1;
    sc_signal< sc_lv<28> > p_Val2_1_cast_i_fu_269_p1;
    sc_signal< sc_lv<27> > p_shl_i_fu_298_p3;
    sc_signal< sc_lv<25> > p_shl9_i_fu_309_p3;
    sc_signal< sc_lv<28> > p_shl_cast_i_fu_305_p1;
    sc_signal< sc_lv<28> > p_shl9_cast_i_fu_316_p1;
    sc_signal< sc_lv<28> > p_Val2_2_fu_320_p2;
    sc_signal< sc_lv<29> > p_Val2_2_cast_i_fu_326_p1;
    sc_signal< sc_lv<29> > p_Val2_5_cast_i_fu_330_p1;
    sc_signal< sc_lv<32> > minimumDistance_fu_354_p1;
    sc_signal< sc_lv<1> > tmp_1_i_fu_357_p2;
    sc_signal< sc_lv<32> > minimumDistanceIndex_2_fu_350_p1;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state19;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_7FFFFFFF;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<9> ap_const_lv9_FF;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state19();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state10_pp0_stage0_iter8();
    void thread_ap_block_state11_pp0_stage0_iter9();
    void thread_ap_block_state12_pp0_stage0_iter10();
    void thread_ap_block_state13_pp0_stage0_iter11();
    void thread_ap_block_state14_pp0_stage0_iter12();
    void thread_ap_block_state15_pp0_stage0_iter13();
    void thread_ap_block_state16_pp0_stage0_iter14();
    void thread_ap_block_state17_pp0_stage0_iter15();
    void thread_ap_block_state18_pp0_stage0_iter16();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_block_state5_pp0_stage0_iter3();
    void thread_ap_block_state6_pp0_stage0_iter4();
    void thread_ap_block_state7_pp0_stage0_iter5();
    void thread_ap_block_state8_pp0_stage0_iter6();
    void thread_ap_block_state9_pp0_stage0_iter7();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_minimumDistanceIndex_phi_fu_106_p4();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_colorBlue_cast_i_fu_222_p1();
    void thread_colorBlue_fu_210_p1();
    void thread_colorGreen_cast_i_fu_219_p1();
    void thread_colorRed_cast_i_cast_fu_192_p3();
    void thread_distance_0_minimumDi_fu_371_p3();
    void thread_exitcond_i_i_fu_167_p2();
    void thread_grp_fxp_sqrt_fu_126_in_val_V_read();
    void thread_i_0_minimumDistanceI_fu_363_p3();
    void thread_i_fu_173_p2();
    void thread_minimumDistanceIndex_2_fu_350_p1();
    void thread_minimumDistance_fu_354_p1();
    void thread_number_assign_1_fu_246_p2();
    void thread_number_assign_2_fu_273_p2();
    void thread_number_assign_fu_214_p2();
    void thread_p_Val2_1_cast_i_fu_269_p1();
    void thread_p_Val2_1_fu_261_p3();
    void thread_p_Val2_2_cast_i_fu_326_p1();
    void thread_p_Val2_2_fu_320_p2();
    void thread_p_Val2_5_cast_i_fu_330_p1();
    void thread_p_Val2_5_i_fu_292_p2();
    void thread_p_Val2_cast_i_fu_242_p1();
    void thread_p_Val2_s_fu_234_p3();
    void thread_p_color_array_address0();
    void thread_p_color_array_ce0();
    void thread_p_shl9_cast_i_fu_316_p1();
    void thread_p_shl9_i_fu_309_p3();
    void thread_p_shl_cast_i_fu_305_p1();
    void thread_p_shl_i_fu_298_p3();
    void thread_pixelBlue_cast_i_fu_163_p1();
    void thread_pixelBlue_fu_159_p1();
    void thread_pixelGreen_cast_i_fu_155_p1();
    void thread_pixelGreen_fu_145_p4();
    void thread_pixelRed_cast_i_fu_141_p1();
    void thread_pixelRed_fu_131_p4();
    void thread_result3_i_fu_228_p0();
    void thread_result3_i_fu_228_p1();
    void thread_result3_i_fu_228_p2();
    void thread_result_11_i_fu_255_p0();
    void thread_result_11_i_fu_255_p1();
    void thread_result_11_i_fu_255_p2();
    void thread_tmp_1_fu_251_p1();
    void thread_tmp_1_i_fu_357_p2();
    void thread_tmp_75_fu_184_p3();
    void thread_tmp_79_fu_286_p0();
    void thread_tmp_79_fu_286_p1();
    void thread_tmp_79_fu_286_p2();
    void thread_tmp_i_fu_179_p1();
    void thread_tmp_s_fu_225_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
