lappend pragmaStatus0 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getVerticalResult/Row" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'Row' does not exist in function 'getVerticalResult'. "}
lappend pragmaStatus1 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getVerticalResult/Col" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'Col' does not exist in function 'getVerticalResult'. "}
lappend pragmaStatus2 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getHorizontalResult/Row" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'Row' does not exist in function 'getHorizontalResult'. "}
lappend pragmaStatus3 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getHorizontalResult/Col" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'Col' does not exist in function 'getHorizontalResult'. "}
lappend pragmaStatus4 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getVerticalResult/Row_Vert" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getVerticalResult/Col_Vert" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getHorizontalResult/Row_Horiz" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getHorizontalResult/Col_Horiz" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "DATAFLOW" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
