lappend pragmaStatus0 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/COL_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "LOOP_FLATTEN" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/REASSIGNMENT_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "ARRAY_RESHAPE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file." variable "pixelArray"}
lappend pragmaStatus5 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'getPixelClassification' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'getPixelClassification' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification_Stream/PIXEL_COLOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'getPixelClassification_Stream' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification_Stream/PIXEL_COLOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'getPixelClassification_Stream' does not exist in any synthesis source file."}
lappend pragmaStatus9 {pragma "INTERFACE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification_Stream" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'getPixelClassification_Stream' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "INTERFACE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification_Stream" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'getPixelClassification_Stream' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "ARRAY_PARTITION" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification_Stream" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'getPixelClassification_Stream' does not exist in any synthesis source file." variable "_color_array"}
lappend pragmaStatus12 {pragma "INTERFACE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification_Stream" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'getPixelClassification_Stream' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/COL_LOOP" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'COL_LOOP' does not exist in function 'parseColorsToCenterPixel'. "}
lappend pragmaStatus2 {pragma "LOOP_FLATTEN" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/REASSIGNMENT_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "ARRAY_RESHAPE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "pixelArray"}
lappend pragmaStatus5 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification_Stream/PIXEL_COLOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification_Stream/PIXEL_COLOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "INTERFACE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification_Stream" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "INTERFACE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification_Stream" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "ARRAY_PARTITION" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification_Stream" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "_color_array"}
lappend pragmaStatus12 {pragma "INTERFACE" source "D:/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification_Stream" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
