lappend pragmaStatus0 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "FUNCTION_INSTANTIATE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "getPixelClassification" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "distance"}
lappend pragmaStatus4 {pragma "UNROLL" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/COL_LOOP" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'COL_LOOP' does not exist in function 'parseColorsToCenterPixel'. "}
lappend pragmaStatus5 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "UNROLL" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel/REASSIGNMENT_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "ARRAY_RESHAPE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/ColorComparator.cpp" location "parseColorsToCenterPixel" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "pixelArray"}
lappend pragmaStatus0 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'getPixelClassification' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification/PIXEL_COLOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'getPixelClassification' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "FUNCTION_INSTANTIATE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "getPixelClassification" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'FUNCTION_INSTANTIATE' cannot be applied: Function 'getPixelClassification' does not exist in any synthesis source file." variable "distance"}
lappend pragmaStatus4 {pragma "UNROLL" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/COL_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/ROW_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "UNROLL" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel/REASSIGNMENT_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "ARRAY_RESHAPE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/ColorComparator/powerFunction.cpp" location "parseColorsToCenterPixel" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_RESHAPE' cannot be applied: Function 'parseColorsToCenterPixel' does not exist in any synthesis source file." variable "pixelArray"}
