lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/powerFunction.cpp" location "getConvolutionResult/Row_Conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'getConvolutionResult' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/powerFunction.cpp" location "getConvolutionResult/Row_Conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'getConvolutionResult' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "UNROLL" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/powerFunction.cpp" location "getConvolutionResult" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'getConvolutionResult' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/powerFunction.cpp" location "power/Power_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/powerFunction.cpp" location "getConvolutionResult" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'getConvolutionResult' does not exist in any synthesis source file." variable "array"}
lappend pragmaStatus5 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/powerFunction.cpp" location "getConvolutionResult/Col_Conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'getConvolutionResult' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/powerFunction.cpp" location "combineOperatorResults" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'combineOperatorResults' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult/Row_Conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult/Row_Conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "UNROLL" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "power/Power_Loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'power' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "array"}
lappend pragmaStatus5 {pragma "LOOP_FLATTEN" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult/Col_Conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "C:/Users/db217620/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "combineOperatorResults" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
