lappend pragmaStatus0 {pragma "LOOP_FLATTEN" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult2/Row_Conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'getConvolutionResult2' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "LOOP_FLATTEN" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult2/Col_Conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_FLATTEN' cannot be applied: Function 'getConvolutionResult2' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult2/Row_Conv" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'getConvolutionResult2' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "UNROLL" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "LOOP_FLATTEN" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult/Row_Conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult/Row_Conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "LOOP_FLATTEN" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult/Col_Conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "ARRAY_PARTITION" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "getConvolutionResult" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "array"}
lappend pragmaStatus8 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "combineOperatorResults" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PIPELINE" source "D:/Repositories/FPGAColorIdentifier/SobelMatrixMultiplier/SobelMatrixMultiplier.cpp" location "power/Power_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
